config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do 
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do 
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: [:show, :index, :create, :update, :destroy]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  
  has_many :order_items

  validates :name, :weight, :width, :height, :depth, :sku, presence: true
  validates :sku, uniqueness: true
  validates :sku, length: { is: 20 }
  validates :weight, :width, :height, :depth, numericality: { greater_than: 0 } 
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
    before_action :set_product_model, only: [:show, :edit, :update]
    before_action :authenticate_user!, only: [:index]
    
    def index 
        @product_models = ProductModel.all
    end

    def new
        @product_model = ProductModel.new
        @suppliers = Supplier.all
    end

    def create 
        @product_model = ProductModel.new(product_model_params)

       if @product_model.save
        redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso'
       else 
        @suppliers = Supplier.all
        flash.now[:notice] = 'Ocorreu um erro ao cadastrar modelo de produto'
        render 'new'
       end
    end

    def show; end

    private 

    def set_product_model
        @product_model = ProductModel.find(params[:id])
    end

    def product_model_params 
        @product_model_params = params.require(:product_model).permit(:name,
                                                                      :weight,
                                                                      :width,
                                                                      :height,
                                                                      :depth,
                                                                      :sku,
                                                                      :supplier_id)
    end
end

app/views/product_models/_form.html.erb
<%= form_with(model: @product_model) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %> 
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width %> 
  </div>
  <div>
    <%= f.label :height %>
    <%= f.number_field :height %> 
  </div>
  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %> 
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %> 
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/product_models/index.html.erb
<h1>Modelos de produtos</h1>

<% if @product_models.any? %>
    <table>
        <thead>
            <tr>
                <th>Produto</th>
                <th>Fabricante</th>
                <th>SKU</th>
            </tr>
        </thead>
        <tbody>
            <% @product_models.each do |pm| %>
                <tr>
                    <td><%= pm.name %></td>
                    <td><%=  pm.supplier.brand_name %><td>
                    <td><%= pm.sku %><td>
                <tr>
            <% end %>
        </tbody>
    </table>
<% else %>
<div>
    <h5>Não há nenhum modelo de produto cadastrado</h5>
</div>
<% end %>
<div>
    <p><%= link_to 'Cadastrar modelo de produto', new_product_model_path %></p>
</div>

app/views/product_models/new.html.erb
<h1>Cadastro de modelo de produtos</h1>

<% if @product_model.errors.any? %>

    <p>Verifique os erros abaixo:</p>
        <ul>
            <% @product_model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>  
            <% end %>
        </ul>
<% end %>

<%= render 'form' %>

app/views/product_models/show.html.erb
<h1>Modelo de produto:</h1>
<p><%= ProductModel.human_attribute_name(:name) %>: <%= @product_model.name %></p>
<p><%= ProductModel.human_attribute_name(:weight) %>: <%= @product_model.weight %>g</p>
<p>Dimensões: <%= @product_model.width %>cm x <%= @product_model.height %>cm x <%= @product_model.depth %>cm</p>
<p><%= ProductModel.human_attribute_name(:sku) %>: <%= @product_model.sku %></p>
<p><%= ProductModel.human_attribute_name(:supplier_id) %>: <%= @product_model.supplier.brand_name %></p>