config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do 
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do 
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: [:show, :index, :create, :update, :destroy]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user

  has_many :order_items
  
  enum status: { pending: 0, delivered: 5, canceled: 9 } 

  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_true

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_true 
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, ' deve ser futura')
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController  
  before_action :set_order, only: [:show, :edit, :update, :delivered, :canceled]
  before_action :authenticate_user!

  def index 
    @orders = current_user.orders
  end

  def new 
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create 
    @order = Order.new(set_params)
    @order.user = current_user
    if @order.save
      redirect_to @order, notice: 'Pedido cadastrado com sucesso'
    else  
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:alert] = 'Não foi possível cadastrar o pedido'
      render :new
    end
  end

  def show
    if @order.user != current_user
      redirect_to root_path, alert: 'Você não possui acesso a este pedido'
    end
    
  end

  def search 
    @code = params[:query]
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  def edit 
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
    if @order.user != current_user
      redirect_to root_path, alert: "Você não tem permissão para editar este pedido"
    end
  end

  def update 
    if @order.user != current_user
      return redirect_to root_path, alert: "Você não tem permissão para editar este pedido"
    else 
      
    end
    if @order.update(set_params)
      redirect_to @order, notice: 'Pedido atualizado com sucesso'
    end
  end

  def delivered 
    @order.delivered!

    @order.order_items.each do |item|
      item.quantity.times do 
        StockProduct.create!(order: @order,
                            product_model: item.product_model,
                            warehouse: @order.warehouse)
      end
    end

    redirect_to @order
  end

  def canceled 
    @order.canceled!
    redirect_to @order
  end
  
  private 

  def set_order
    @order = Order.find(params[:id])
  end

  def set_params 
    @set_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |f| %>
  <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>  
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :full_description %>
  </div>
  <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>
  <div>
    <%= f.submit 'Gravar' %>
  </div>
<% end %>

app/views/orders/_order.html.erb
  <p><%= Order.human_attribute_name(:code) %>: <%= link_to order.code, order %><p>
  <p><%= Order.human_attribute_name(:warehouse) %>: <%= order.warehouse.name %><p>
  <p><%= Order.human_attribute_name(:supplier) %>: <%= order.supplier.full_description %><p>
  <p><%= Order.human_attribute_name(:user) %>: <%= order.user.name %> | <%= order.user.email %><p>
  <p><%= Order.human_attribute_name(:status) %>: <%= I18n.t(order.status) %><p>

app/views/orders/edit.html.erb
<h1>Edite o pedido</h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Meus pedidos</h1>


<% @orders.each do |order| %>
  <%= render order %>
<% end %>

app/views/orders/new.html.erb
<h1>Registrar Pedido</h1>

<% if @order.errors.any? %>

    <p>Verifique os erros abaixo:</p>
        <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>  
            <% end %>
        </ul>
<% end %>

<%= render 'form' %>

app/views/orders/search.html.erb
<h1>Resultado da pesquisa para o termo '<%= @code %>':</h1>


<h2><%= @orders.count %> <%= Order.model_name.human(count: @orders.count) %> <%= I18n.t(:found, count: @orders.count) %>:</h2>

<% @orders.each do |order| %>
  <%= render order %>
<% end %>

app/views/orders/show.html.erb
<h1><%= Order.model_name.human %> <%= @order.code %></h1>

<p><%= Order.human_attribute_name(:warehouse_id) %>: <%= @order.warehouse.name %></p>
<p><%= Order.human_attribute_name(:supplier_id) %>: <%= @order.supplier.corporate_name %></p>
<p><%= Order.human_attribute_name(:user_id) %>: <%= @order.user.name %> | <%= @order.user.email %></p>
<p><%= Order.human_attribute_name(:estimated_delivery_date) %>: <%= I18n.localize(@order.estimated_delivery_date) %></p>
<p><%= Order.human_attribute_name(:status) %>: <%= I18n.t(@order.status) %></p>

<h3><%= link_to 'Adicionar item', new_order_order_item_path(order_id: @order.id) %> </h3>

<% if @order.order_items.any? %>
  <h2>Itens do pedido:</h2>
  <% @order.order_items.each do |oi| %>
    <p><%= oi.quantity %> x <%= oi.product_model.name %></p>
  <% end %>
<% end %>

<% if @order.pending? %>
  <%= button_to 'Marcar como entregue', delivered_order_path(@order.id) %>
  <%= button_to 'Cancelar pedido', canceled_order_path(@order.id) %>
<% end %>

<div>
  <%= link_to 'Editar', edit_order_path(@order.id) %>
</div>