config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do 
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]

  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do 
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do 
    namespace :v1 do 
      resources :warehouses, only: [:show, :index, :create, :update, :destroy]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true
  validates :registration_number, :email, uniqueness: true
  validates :registration_number, length: { is: 13 }

  def full_description 
    "#{corporate_name} | #{brand_name}"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController 
    before_action :set_supplier, only: [:show, :edit, :update]

    def index
      @suppliers = Supplier.all
    end

    def new
       @supplier = Supplier.new
    end

    def create 
      @supplier = Supplier.new(supplier_params)
      
      if @supplier.save
        redirect_to suppliers_path, notice: 'Fornecedor cadastrado com sucesso'
      else 
        flash[:notice] = 'Nenhum fornecedor cadastrado' 
        render 'new'
      end
    end

    def show; end

    def edit; end

    def update 
      if @supplier.update(supplier_params)
        redirect_to supplier_path(@supplier), notice: 'Fornecedor atualizado com sucesso'
      else  
        flash.now[:notice] = 'Não foi possível atualizar o fornecedor'
        render 'edit'
      end
    end

    private 
    
    def set_supplier 
      @supplier = Supplier.find(params[:id])
    end

    def supplier_params
      @supplier_params = params.require(:supplier).permit(:corporate_name, 
                                                          :brand_name, 
                                                          :registration_number,
                                                          :full_address, 
                                                          :city, 
                                                          :state, 
                                                          :email)
    end
end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
    <div>
        <%= f.label :corporate_name, 'Razão social' %>
        <%= f.text_field :corporate_name %>
    </div>
    <div>
        <%= f.label :brand_name, 'Nome fantasia' %>
        <%= f.text_field :brand_name %>
    </div>
    <div>
        <%= f.label :registration_number, 'CNPJ' %>
        <%= f.number_field :registration_number %>
    </div>
    <div>
        <%= f.label :full_address, 'Endereço' %>
        <%= f.text_field :full_address %>
    </div>
    <div>
        <%= f.label :city, 'Cidade' %>
        <%= f.text_field :city %>
    </div>
    <div>
        <%= f.label :state, 'Estado' %>
        <%= f.text_field :state %>
    </div>
    <div>
        <%= f.label :email, 'Email' %>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.submit 'Enviar' %>    
    </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Fornecedores: </h1>

<% if @suppliers.any? %>
    <table>
        <thead>
            <tr>
                <th>Fornecedor</th>
                <th>Localização</th>
            </tr>
        </thead>
        <tbody>
            <% @suppliers.each do |s| %>
                <tr>
                    <td><%= link_to s.corporate_name, s %><td>
                    <td><%= s.full_address %><td>
                <tr>
            <% end %>
        </tbody>
    </table>
<% else %>
<div>
    <h5>Nenhum fornecedor cadastrado</h5>
</div>
<% end %>
<div>
    <li><%= link_to 'Novo Fornecedor',new_supplier_path %></li>
</div>
<div>
    <p><%= link_to('Início', root_path) %></p>
</div>

app/views/suppliers/new.html.erb
<h1>Cadastro de fornecedor:</h1>

<% if @supplier.errors.any? %>

    <p>Verifique os erros abaixo:</p>
        <ul>
            <% @supplier.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>  
            <% end %>
        </ul>
<% end %>
<%= render 'form' %>
<div>
    <p><%= link_to('Início', root_path) %></p>
</div>

app/views/suppliers/show.html.erb
<h1><%= Supplier.model_name.human %> <%= @supplier.registration_number %></h1>
<p><%= Supplier.human_attribute_name(:corporate_name) %>: <%= @supplier.corporate_name %></p>
<p><%= Supplier.human_attribute_name(:brand_name) %>: <%= @supplier.brand_name %></p>
<p><%= Supplier.human_attribute_name(:full_address) %>: <%= @supplier.full_address %></p>
<p><%= Supplier.human_attribute_name(:registration_number) %>: <%= @supplier.registration_number %></p>
<p><%= Supplier.human_attribute_name(:city) %>: <%= @supplier.city %></p>
<p><%= Supplier.human_attribute_name(:state) %>: <%= @supplier.state %></p>
<p><%= Supplier.human_attribute_name(:email) %>: <%= @supplier.email %></p>


<div>
    <p><%= link_to('Editar Fornecedor', edit_supplier_path(@supplier.id)) %></p>
</div>
<div>
    <p><%= link_to('Início', root_path) %></p>
</div>